<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit34ebc036609d3838aeed54ddbf74a22e
{
    public static $prefixLengthsPsr4 = array (
        't' => 
        array (
            'tmntzpizza\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'tmntzpizza\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit34ebc036609d3838aeed54ddbf74a22e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit34ebc036609d3838aeed54ddbf74a22e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit34ebc036609d3838aeed54ddbf74a22e::$classMap;

        }, null, ClassLoader::class);
    }
}
